AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'config/initializers/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'lib/tasks/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/support/*'
    - 'spec/active_support_callbacks_spec.rb'
    - 'rails-workflow.gemspec'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 14

Lint/Eval:
  Exclude:
    - 'lib/workflow/callbacks/string_callback.rb'
    - 'lib/workflow/callbacks/transition_callbacks/method_wrapper.rb'
    - 'lib/workflow/callbacks/transition_callbacks/proc_wrapper.rb'
