# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rails Workflow
email: tyler@aprilseven.co
description: > # this means to ignore newlines until "baseurl:"
  Rails Workflow began as a fork of the Workflow gem by Vladimir Dobriakov.
  It is a nearly total rewrite but maintains the same core architecture.
  It is released under the MIT License.
baseurl: "/rails-workflow" # the subpath of your site, e.g. /blog
# url: "http://localhost:4000/" # the base hostname & protocol for your site
url: ''
twitter_username:
github_username:  tylergannon

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-redirect-from
  - jekyll-toc
whitelist:
  - jekyll-redirect-from
  - jekyll-toc
